package com.somuleco.creator.feature.auth

import android.content.Context
import androidx.credentials.CredentialManager
import androidx.credentials.GetCredentialRequest
import com.google.android.libraries.identity.googleid.GetSignInWithGoogleOption
import com.google.android.libraries.identity.googleid.GoogleIdTokenCredential
import com.somuleco.creator.R

/**
 * Launches the Credential Manager Google Sign-In bottom sheet and returns the resulting Google
 * ID token, ready to be exchanged for a Firebase credential by
 * [AuthViewModel.loginWithGoogle]/[com.somuleco.creator.data.repository.interfaces.AuthRepository.loginWithGoogle]
 * (Foundation Wave 08, plan §7.4 task 5, §13 Decision 8 — Credential Manager's
 * `GetSignInWithGoogleOption`, not the deprecated Play Services Auth Google Sign-In SDK).
 * Mirrors Somuleco Connect's proven `ui/screens/GoogleSignInHelper.kt` near-verbatim.
 *
 * Requires an Activity [Context], so this stays a plain suspend function called from the Compose
 * layer (`LocalContext.current`) rather than living on the repository/ViewModel.
 *
 * The Web client ID (`client_type: 3` OAuth client) is resolved from
 * `R.string.default_web_client_id`, generated by the `google-services` Gradle plugin from
 * `app/google-services.json` at build time. That file is currently a hand-authored,
 * non-functional local/emulator placeholder (see its own header comment) — this compiles and
 * runs the full Credential Manager flow, but the resulting Google Sign-In exchange cannot
 * actually succeed against Google's real servers until Creator Android is registered as a real
 * app in the shared `somuleco-firebase` project (disclosed, non-blocking follow-up).
 */
suspend fun requestGoogleIdToken(context: Context): Result<String> = runCatching {
    val webClientId = context.getString(R.string.default_web_client_id)
    val option = GetSignInWithGoogleOption.Builder(webClientId).build()
    val request = GetCredentialRequest.Builder()
        .addCredentialOption(option)
        .build()

    val credentialManager = CredentialManager.create(context)
    val response = credentialManager.getCredential(context, request)
    val googleIdTokenCredential = GoogleIdTokenCredential.createFrom(response.credential.data)
    googleIdTokenCredential.idToken
}
